server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_spring_security?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 