spring:
  profiles:
    active: dev
#    active: prod
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        format_sql: true
    defer-datasource-initialization: true # Initialize the datasource with available DDL and DML scripts
  sql:
    init:
      mode: always # Initialize the datasource with available DDL and DML scripts
#  mail:
#    default-encoding: UTF-8
#    host: smtp.gmail.com
#    username: email@email.email
#    password: password
#    port: 587
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#    protocol: smtp
#    test-connection: false

## Hibernate Logging 
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG

security:    
  jwt:
    secret-key: my@app
    expiration: 3600000 # 60 minutes duration by default: 60 minutes * 60 seconds * 1000 milliseconds

app:
  user:
    token:
      expiration: 7200000 # 120 minutes duration by default: 2 hours * 60 minutes * 60 seconds * 1000 milliseconds
  cors: 
#    allowedOrigins: http://localhost:3000
    allowedOrigins:
  url:
#    base: http://localhost:8080/
    base:
#    frontend: http://localhost:3000/
    frontend:
  email:
    #    host: smtp.mailtrap.io
    #    port: 25
    host: smtp.gmail.com
    port: 587
    address:
    password: